# This file provides instructions for packaging.

`Plack-Middleware-Auth-Bitcard`
	perl_version_from m`Plack::Middleware::Auth::Bitcard`;
	version_from      m`Plack::Middleware::Auth::Bitcard`;
	readme_from       m`Plack::Middleware::Auth::Bitcard`;
	requires          p`Authen::Bitcard 0`;
	requires          p`JSON 2.00`;
	requires          p`Plack 1.0000`;
	test_requires     p`HTTP::Request::Common 0`;
	test_requires     p`URI 0`;
	test_requires     p`URI::QueryParam 0`;
	.

